// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';
import type { QueryOperationTypes as PgTargetQueryOps } from '@prisma/orm-postgres/target/operation-types';

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'ee1af0dba6271fff6e7a44dc23293510289f55b58f3783e8c0f6f8ee68dd2743'>;
export type ExecutionHash =
  ExecutionHashBase<'a094107ad9f461fb666cdc00c019775edd5796ce29409458da82ca1da5498038'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgTargetQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-date@1': {
        readonly output: 'pg/timestamptz-date@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-date@1': {
        readonly output: 'pg/timestamptz-date@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Cliente: {
      readonly criadoEm: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly pontos: CodecTypes['pg/int4@1']['output'];
      readonly telefone: CodecTypes['pg/text@1']['output'] | null;
      readonly usuarioId: CodecTypes['pg/text@1']['output'];
    };
    readonly Estoque: {
      readonly atualizadoEm: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly produtoId: CodecTypes['pg/text@1']['output'];
      readonly quantidade: CodecTypes['pg/int4@1']['output'];
      readonly unidadeId: CodecTypes['pg/text@1']['output'];
    };
    readonly ItemPedido: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly pedidoId: CodecTypes['pg/text@1']['output'];
      readonly precoUnitario: CodecTypes['pg/numeric@1']['output'];
      readonly produtoId: CodecTypes['pg/text@1']['output'];
      readonly quantidade: CodecTypes['pg/int4@1']['output'];
      readonly subtotal: CodecTypes['pg/numeric@1']['output'];
    };
    readonly Pedido: {
      readonly atualizadoEm: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly canalPedido: 'APP' | 'TOTEM' | 'BALCAO' | 'PICKUP' | 'WEB';
      readonly clienteId: CodecTypes['pg/text@1']['output'] | null;
      readonly criadoEm: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly status:
        | 'CRIADO'
        | 'AGUARDANDO_PAGAMENTO'
        | 'PAGO'
        | 'EM_PREPARACAO'
        | 'PRONTO'
        | 'ENTREGUE'
        | 'CANCELADO';
      readonly unidadeId: CodecTypes['pg/text@1']['output'];
      readonly valorTotal: CodecTypes['pg/numeric@1']['output'];
    };
    readonly Produto: {
      readonly ativo: CodecTypes['pg/bool@1']['output'];
      readonly descricao: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly nome: CodecTypes['pg/text@1']['output'];
      readonly preco: CodecTypes['pg/numeric@1']['output'];
    };
    readonly Unidade: {
      readonly ativo: CodecTypes['pg/bool@1']['output'];
      readonly endereco: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly nome: CodecTypes['pg/text@1']['output'];
    };
    readonly Usuario: {
      readonly ativo: CodecTypes['pg/bool@1']['output'];
      readonly criadoEm: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly nome: CodecTypes['pg/text@1']['output'];
      readonly perfil: CodecTypes['pg/text@1']['output'];
      readonly senhaHash: CodecTypes['pg/text@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Cliente: {
      readonly criadoEm: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly pontos: CodecTypes['pg/int4@1']['input'];
      readonly telefone: CodecTypes['pg/text@1']['input'] | null;
      readonly usuarioId: CodecTypes['pg/text@1']['input'];
    };
    readonly Estoque: {
      readonly atualizadoEm: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly produtoId: CodecTypes['pg/text@1']['input'];
      readonly quantidade: CodecTypes['pg/int4@1']['input'];
      readonly unidadeId: CodecTypes['pg/text@1']['input'];
    };
    readonly ItemPedido: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly pedidoId: CodecTypes['pg/text@1']['input'];
      readonly precoUnitario: CodecTypes['pg/numeric@1']['input'];
      readonly produtoId: CodecTypes['pg/text@1']['input'];
      readonly quantidade: CodecTypes['pg/int4@1']['input'];
      readonly subtotal: CodecTypes['pg/numeric@1']['input'];
    };
    readonly Pedido: {
      readonly atualizadoEm: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly canalPedido: 'APP' | 'TOTEM' | 'BALCAO' | 'PICKUP' | 'WEB';
      readonly clienteId: CodecTypes['pg/text@1']['input'] | null;
      readonly criadoEm: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly status:
        | 'CRIADO'
        | 'AGUARDANDO_PAGAMENTO'
        | 'PAGO'
        | 'EM_PREPARACAO'
        | 'PRONTO'
        | 'ENTREGUE'
        | 'CANCELADO';
      readonly unidadeId: CodecTypes['pg/text@1']['input'];
      readonly valorTotal: CodecTypes['pg/numeric@1']['input'];
    };
    readonly Produto: {
      readonly ativo: CodecTypes['pg/bool@1']['input'];
      readonly descricao: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly nome: CodecTypes['pg/text@1']['input'];
      readonly preco: CodecTypes['pg/numeric@1']['input'];
    };
    readonly Unidade: {
      readonly ativo: CodecTypes['pg/bool@1']['input'];
      readonly endereco: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly nome: CodecTypes['pg/text@1']['input'];
    };
    readonly Usuario: {
      readonly ativo: CodecTypes['pg/bool@1']['input'];
      readonly criadoEm: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly nome: CodecTypes['pg/text@1']['input'];
      readonly perfil: CodecTypes['pg/text@1']['input'];
      readonly senhaHash: CodecTypes['pg/text@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly Cliente: {
      readonly criadoEm: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly pontos: CodecTypes['pg/int4@1']['output'];
      readonly telefone: CodecTypes['pg/text@1']['output'] | null;
      readonly usuarioId: CodecTypes['pg/text@1']['output'];
    };
    readonly Estoque: {
      readonly atualizadoEm: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly produtoId: CodecTypes['pg/text@1']['output'];
      readonly quantidade: CodecTypes['pg/int4@1']['output'];
      readonly unidadeId: CodecTypes['pg/text@1']['output'];
    };
    readonly ItemPedido: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly pedidoId: CodecTypes['pg/text@1']['output'];
      readonly precoUnitario: CodecTypes['pg/numeric@1']['output'];
      readonly produtoId: CodecTypes['pg/text@1']['output'];
      readonly quantidade: CodecTypes['pg/int4@1']['output'];
      readonly subtotal: CodecTypes['pg/numeric@1']['output'];
    };
    readonly Pedido: {
      readonly atualizadoEm: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly canalPedido: 'APP' | 'TOTEM' | 'BALCAO' | 'PICKUP' | 'WEB';
      readonly clienteId: CodecTypes['pg/text@1']['output'] | null;
      readonly criadoEm: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly status:
        | 'CRIADO'
        | 'AGUARDANDO_PAGAMENTO'
        | 'PAGO'
        | 'EM_PREPARACAO'
        | 'PRONTO'
        | 'ENTREGUE'
        | 'CANCELADO';
      readonly unidadeId: CodecTypes['pg/text@1']['output'];
      readonly valorTotal: CodecTypes['pg/numeric@1']['output'];
    };
    readonly Produto: {
      readonly ativo: CodecTypes['pg/bool@1']['output'];
      readonly descricao: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly nome: CodecTypes['pg/text@1']['output'];
      readonly preco: CodecTypes['pg/numeric@1']['output'];
    };
    readonly Unidade: {
      readonly ativo: CodecTypes['pg/bool@1']['output'];
      readonly endereco: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly nome: CodecTypes['pg/text@1']['output'];
    };
    readonly Usuario: {
      readonly ativo: CodecTypes['pg/bool@1']['output'];
      readonly criadoEm: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly nome: CodecTypes['pg/text@1']['output'];
      readonly perfil: CodecTypes['pg/text@1']['output'];
      readonly senhaHash: CodecTypes['pg/text@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly Cliente: {
      readonly criadoEm: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly pontos: CodecTypes['pg/int4@1']['input'];
      readonly telefone: CodecTypes['pg/text@1']['input'] | null;
      readonly usuarioId: CodecTypes['pg/text@1']['input'];
    };
    readonly Estoque: {
      readonly atualizadoEm: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly produtoId: CodecTypes['pg/text@1']['input'];
      readonly quantidade: CodecTypes['pg/int4@1']['input'];
      readonly unidadeId: CodecTypes['pg/text@1']['input'];
    };
    readonly ItemPedido: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly pedidoId: CodecTypes['pg/text@1']['input'];
      readonly precoUnitario: CodecTypes['pg/numeric@1']['input'];
      readonly produtoId: CodecTypes['pg/text@1']['input'];
      readonly quantidade: CodecTypes['pg/int4@1']['input'];
      readonly subtotal: CodecTypes['pg/numeric@1']['input'];
    };
    readonly Pedido: {
      readonly atualizadoEm: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly canalPedido: 'APP' | 'TOTEM' | 'BALCAO' | 'PICKUP' | 'WEB';
      readonly clienteId: CodecTypes['pg/text@1']['input'] | null;
      readonly criadoEm: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly status:
        | 'CRIADO'
        | 'AGUARDANDO_PAGAMENTO'
        | 'PAGO'
        | 'EM_PREPARACAO'
        | 'PRONTO'
        | 'ENTREGUE'
        | 'CANCELADO';
      readonly unidadeId: CodecTypes['pg/text@1']['input'];
      readonly valorTotal: CodecTypes['pg/numeric@1']['input'];
    };
    readonly Produto: {
      readonly ativo: CodecTypes['pg/bool@1']['input'];
      readonly descricao: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly nome: CodecTypes['pg/text@1']['input'];
      readonly preco: CodecTypes['pg/numeric@1']['input'];
    };
    readonly Unidade: {
      readonly ativo: CodecTypes['pg/bool@1']['input'];
      readonly endereco: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly nome: CodecTypes['pg/text@1']['input'];
    };
    readonly Usuario: {
      readonly ativo: CodecTypes['pg/bool@1']['input'];
      readonly criadoEm: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly nome: CodecTypes['pg/text@1']['input'];
      readonly perfil: CodecTypes['pg/text@1']['input'];
      readonly senhaHash: CodecTypes['pg/text@1']['input'];
    };
  };
};

export namespace Models {
  export type public_Cliente = {
    criadoEm: CodecTypes['pg/timestamptz-string@1']['output'];
    id: CodecTypes['pg/text@1']['output'];
    pontos: CodecTypes['pg/int4@1']['output'];
    telefone: CodecTypes['pg/text@1']['output'] | null;
    usuarioId: CodecTypes['pg/text@1']['output'];
    usuario: public_Usuario;
    readonly [RelationKeys]?: 'usuario';
  };
  export type public_Estoque = {
    atualizadoEm: CodecTypes['pg/timestamptz-string@1']['output'];
    id: CodecTypes['pg/text@1']['output'];
    produtoId: CodecTypes['pg/text@1']['output'];
    quantidade: CodecTypes['pg/int4@1']['output'];
    unidadeId: CodecTypes['pg/text@1']['output'];
    produto: public_Produto;
    unidade: public_Unidade;
    readonly [RelationKeys]?: 'produto' | 'unidade';
  };
  export type public_ItemPedido = {
    id: CodecTypes['pg/text@1']['output'];
    pedidoId: CodecTypes['pg/text@1']['output'];
    precoUnitario: CodecTypes['pg/numeric@1']['output'];
    produtoId: CodecTypes['pg/text@1']['output'];
    quantidade: CodecTypes['pg/int4@1']['output'];
    subtotal: CodecTypes['pg/numeric@1']['output'];
    pedido: public_Pedido;
    produto: public_Produto;
    readonly [RelationKeys]?: 'pedido' | 'produto';
  };
  export type public_Pedido = {
    atualizadoEm: CodecTypes['pg/timestamptz-string@1']['output'];
    canalPedido: 'APP' | 'TOTEM' | 'BALCAO' | 'PICKUP' | 'WEB';
    clienteId: CodecTypes['pg/text@1']['output'] | null;
    criadoEm: CodecTypes['pg/timestamptz-string@1']['output'];
    id: CodecTypes['pg/text@1']['output'];
    status:
      | 'CRIADO'
      | 'AGUARDANDO_PAGAMENTO'
      | 'PAGO'
      | 'EM_PREPARACAO'
      | 'PRONTO'
      | 'ENTREGUE'
      | 'CANCELADO';
    unidadeId: CodecTypes['pg/text@1']['output'];
    valorTotal: CodecTypes['pg/numeric@1']['output'];
    cliente: public_Cliente | null;
    itens: public_ItemPedido[];
    unidade: public_Unidade;
    readonly [RelationKeys]?: 'cliente' | 'itens' | 'unidade';
  };
  export type public_Produto = {
    ativo: CodecTypes['pg/bool@1']['output'];
    descricao: CodecTypes['pg/text@1']['output'] | null;
    id: CodecTypes['pg/text@1']['output'];
    nome: CodecTypes['pg/text@1']['output'];
    preco: CodecTypes['pg/numeric@1']['output'];
    estoques: public_Estoque[];
    readonly [RelationKeys]?: 'estoques';
  };
  export type public_Unidade = {
    ativo: CodecTypes['pg/bool@1']['output'];
    endereco: CodecTypes['pg/text@1']['output'] | null;
    id: CodecTypes['pg/text@1']['output'];
    nome: CodecTypes['pg/text@1']['output'];
    estoques: public_Estoque[];
    readonly [RelationKeys]?: 'estoques';
  };
  export type public_Usuario = {
    ativo: CodecTypes['pg/bool@1']['output'];
    criadoEm: CodecTypes['pg/timestamptz-string@1']['output'];
    email: CodecTypes['pg/text@1']['output'];
    id: CodecTypes['pg/text@1']['output'];
    nome: CodecTypes['pg/text@1']['output'];
    perfil: CodecTypes['pg/text@1']['output'];
    senhaHash: CodecTypes['pg/text@1']['output'];
    cliente: public_Cliente | null;
    readonly [RelationKeys]?: 'cliente';
  };
}

export declare const models: {
  public: {
    Cliente: Models.public_Cliente;
    Estoque: Models.public_Estoque;
    ItemPedido: Models.public_ItemPedido;
    Pedido: Models.public_Pedido;
    Produto: Models.public_Produto;
    Unidade: Models.public_Unidade;
    Usuario: Models.public_Usuario;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly Cliente: {
              columns: {
                readonly criadoEm: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly pontos: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 0>;
                  };
                };
                readonly telefone: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly usuarioId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['usuarioId'] }];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Cliente';
                    readonly columns: readonly ['usuarioId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Usuario';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly Estoque: {
              columns: {
                readonly atualizadoEm: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly produtoId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly quantidade: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 0>;
                  };
                };
                readonly unidadeId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['unidadeId', 'produtoId'] }];
              indexes: readonly [
                {
                  readonly name: 'Estoque_produtoId_idx_eb62fdb9';
                  readonly prefix: 'Estoque_produtoId_idx';
                  readonly columns: readonly ['produtoId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'Estoque_unidadeId_idx_af675c1c';
                  readonly prefix: 'Estoque_unidadeId_idx';
                  readonly columns: readonly ['unidadeId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Estoque';
                    readonly columns: readonly ['unidadeId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Unidade';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Estoque';
                    readonly columns: readonly ['produtoId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Produto';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly ItemPedido: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly pedidoId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly precoUnitario: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: false;
                };
                readonly produtoId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly quantidade: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly subtotal: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'ItemPedido_pedidoId_idx_4742647d';
                  readonly prefix: 'ItemPedido_pedidoId_idx';
                  readonly columns: readonly ['pedidoId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'ItemPedido_produtoId_idx_eb62fdb9';
                  readonly prefix: 'ItemPedido_produtoId_idx';
                  readonly columns: readonly ['produtoId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'ItemPedido';
                    readonly columns: readonly ['pedidoId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Pedido';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'ItemPedido';
                    readonly columns: readonly ['produtoId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Produto';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly Pedido: {
              columns: {
                readonly atualizadoEm: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly canalPedido: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly clienteId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly criadoEm: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'CRIADO'>;
                  };
                };
                readonly unidadeId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly valorTotal: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'Pedido_clienteId_idx_7ae16308';
                  readonly prefix: 'Pedido_clienteId_idx';
                  readonly columns: readonly ['clienteId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'Pedido_unidadeId_idx_af675c1c';
                  readonly prefix: 'Pedido_unidadeId_idx';
                  readonly columns: readonly ['unidadeId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Pedido';
                    readonly columns: readonly ['clienteId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Cliente';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Pedido';
                    readonly columns: readonly ['unidadeId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Unidade';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly Produto: {
              columns: {
                readonly ativo: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', true>;
                  };
                };
                readonly descricao: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly nome: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly preco: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly Unidade: {
              columns: {
                readonly ativo: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', true>;
                  };
                };
                readonly endereco: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly nome: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly Usuario: {
              columns: {
                readonly ativo: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', true>;
                  };
                };
                readonly criadoEm: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly nome: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly perfil: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly senhaHash: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['email'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
          readonly valueSet: {
            readonly CanalPedido: {
              readonly kind: 'valueSet';
              readonly values: readonly ['APP', 'TOTEM', 'BALCAO', 'PICKUP', 'WEB'];
            };
            readonly StatusPedido: {
              readonly kind: 'valueSet';
              readonly values: readonly [
                'CRIADO',
                'AGUARDANDO_PAGAMENTO',
                'PAGO',
                'EM_PREPARACAO',
                'PRONTO',
                'ENTREGUE',
                'CANCELADO',
              ];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly Cliente: { readonly namespace: 'public' & NamespaceId; readonly model: 'Cliente' };
    readonly Estoque: { readonly namespace: 'public' & NamespaceId; readonly model: 'Estoque' };
    readonly ItemPedido: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'ItemPedido';
    };
    readonly Pedido: { readonly namespace: 'public' & NamespaceId; readonly model: 'Pedido' };
    readonly Produto: { readonly namespace: 'public' & NamespaceId; readonly model: 'Produto' };
    readonly Unidade: { readonly namespace: 'public' & NamespaceId; readonly model: 'Unidade' };
    readonly Usuario: { readonly namespace: 'public' & NamespaceId; readonly model: 'Usuario' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Cliente: {
            readonly fields: {
              readonly criadoEm: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly pontos: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly telefone: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly usuarioId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly usuario: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Usuario';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['usuarioId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'Cliente';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly criadoEm: { readonly column: 'criadoEm' };
                readonly id: { readonly column: 'id' };
                readonly pontos: { readonly column: 'pontos' };
                readonly telefone: { readonly column: 'telefone' };
                readonly usuarioId: { readonly column: 'usuarioId' };
              };
            };
          };
          readonly Estoque: {
            readonly fields: {
              readonly atualizadoEm: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly produtoId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly quantidade: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly unidadeId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly produto: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Produto';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['produtoId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly unidade: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Unidade';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['unidadeId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'Estoque';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly atualizadoEm: { readonly column: 'atualizadoEm' };
                readonly id: { readonly column: 'id' };
                readonly produtoId: { readonly column: 'produtoId' };
                readonly quantidade: { readonly column: 'quantidade' };
                readonly unidadeId: { readonly column: 'unidadeId' };
              };
            };
          };
          readonly ItemPedido: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly pedidoId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly precoUnitario: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly produtoId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly quantidade: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly subtotal: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
            };
            readonly relations: {
              readonly pedido: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Pedido';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['pedidoId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly produto: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Produto';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['produtoId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'ItemPedido';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly pedidoId: { readonly column: 'pedidoId' };
                readonly precoUnitario: { readonly column: 'precoUnitario' };
                readonly produtoId: { readonly column: 'produtoId' };
                readonly quantidade: { readonly column: 'quantidade' };
                readonly subtotal: { readonly column: 'subtotal' };
              };
            };
          };
          readonly Pedido: {
            readonly fields: {
              readonly atualizadoEm: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly canalPedido: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly clienteId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly criadoEm: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly unidadeId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly valorTotal: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
            };
            readonly relations: {
              readonly cliente: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Cliente';
                };
                readonly cardinality: 'N:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['clienteId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly itens: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'ItemPedido';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['pedidoId'];
                };
              };
              readonly unidade: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Unidade';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['unidadeId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'Pedido';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly atualizadoEm: { readonly column: 'atualizadoEm' };
                readonly canalPedido: { readonly column: 'canalPedido' };
                readonly clienteId: { readonly column: 'clienteId' };
                readonly criadoEm: { readonly column: 'criadoEm' };
                readonly id: { readonly column: 'id' };
                readonly status: { readonly column: 'status' };
                readonly unidadeId: { readonly column: 'unidadeId' };
                readonly valorTotal: { readonly column: 'valorTotal' };
              };
            };
          };
          readonly Produto: {
            readonly fields: {
              readonly ativo: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly descricao: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly nome: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly preco: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
            };
            readonly relations: {
              readonly estoques: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Estoque';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['produtoId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'Produto';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly ativo: { readonly column: 'ativo' };
                readonly descricao: { readonly column: 'descricao' };
                readonly id: { readonly column: 'id' };
                readonly nome: { readonly column: 'nome' };
                readonly preco: { readonly column: 'preco' };
              };
            };
          };
          readonly Unidade: {
            readonly fields: {
              readonly ativo: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly endereco: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly nome: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly estoques: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Estoque';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['unidadeId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'Unidade';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly ativo: { readonly column: 'ativo' };
                readonly endereco: { readonly column: 'endereco' };
                readonly id: { readonly column: 'id' };
                readonly nome: { readonly column: 'nome' };
              };
            };
          };
          readonly Usuario: {
            readonly fields: {
              readonly ativo: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly criadoEm: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly nome: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly perfil: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly senhaHash: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly cliente: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Cliente';
                };
                readonly cardinality: '1:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['usuarioId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'Usuario';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly ativo: { readonly column: 'ativo' };
                readonly criadoEm: { readonly column: 'criadoEm' };
                readonly email: { readonly column: 'email' };
                readonly id: { readonly column: 'id' };
                readonly nome: { readonly column: 'nome' };
                readonly perfil: { readonly column: 'perfil' };
                readonly senhaHash: { readonly column: 'senhaHash' };
              };
            };
          };
        };
        readonly enum: {
          readonly CanalPedido: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'APP'; readonly value: 'APP' },
              { readonly name: 'TOTEM'; readonly value: 'TOTEM' },
              { readonly name: 'BALCAO'; readonly value: 'BALCAO' },
              { readonly name: 'PICKUP'; readonly value: 'PICKUP' },
              { readonly name: 'WEB'; readonly value: 'WEB' },
            ];
          };
          readonly StatusPedido: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'CRIADO'; readonly value: 'CRIADO' },
              { readonly name: 'AGUARDANDO_PAGAMENTO'; readonly value: 'AGUARDANDO_PAGAMENTO' },
              { readonly name: 'PAGO'; readonly value: 'PAGO' },
              { readonly name: 'EM_PREPARACAO'; readonly value: 'EM_PREPARACAO' },
              { readonly name: 'PRONTO'; readonly value: 'PRONTO' },
              { readonly name: 'ENTREGUE'; readonly value: 'ENTREGUE' },
              { readonly name: 'CANCELADO'; readonly value: 'CANCELADO' },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly insertOnConflictSkip: true;
      readonly insertOnConflictWithoutTarget: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'Cliente';
            readonly field: 'id';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'Estoque';
            readonly field: 'id';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'ItemPedido';
            readonly field: 'id';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'Pedido';
            readonly field: 'id';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'Produto';
            readonly field: 'id';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'Unidade';
            readonly field: 'id';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'Usuario';
            readonly field: 'id';
            readonly namespace: 'public';
          };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
